### ISSUE TITLE
Expand Index confusion

### ISSUE THREAD

**Issue by rfuhrer** [LukaszWatroba/v-accordion#12]
I was using the expand and collapse functions: 
`<v-accordion class="vAccordion--default" onExpand="selectCable(index)" onCollapse="deselectCable(index)">`
and I assumed the "index" in those would be the same as the $index from:
`<v-pane ng-repeat="cable in cables">`
`<md-button ng-disabled="$index === 0" ng-click="swapCable($index,-1)">`
I noticed that they would get out of sync when i would remove a cable from "cables".  Upon digging into your code I discovered that onExpand gets the index of the pane that was clicked on, not the index of the item in the model that was clicked.  These number get out of sync because panes aren't removed from the list of panes, they are just marked "destroyed".

Is there some way to get the actual $index of the selected item in the model instead? You can't just use $index because the onExpand method is declared outside of the ng-repeat

**Comment by rfuhrer** [comment]
So far it seems the easiest way to fix it would be to move onExpand and onCollapse to the v-header tag instead of having it on v-accordion
`<v-accordion onExpand><v-pane ng-repeat><v-header>` changes to `<v-accordion><v-pane ng-repeat><v-header onExpand>`
Then you could use "index" if you wanted the pane index (not really sure why you'd ever want that though) and then "$index" if you needed the index in your ng-repeat.  Unfortunately that would break all existing users of v-accordion, so maybe there's a better way

**Comment by Gratouille** [comment]
+1, got the same problem. We can't remove items from the collection without breaking the accordion :x

**Comment by LukaszWatroba** [comment]
Thanks guys! It should always work that way.

**Comment by shaohaolin** [comment]
I actually added `<v-header onExpand=expandCallback(index) >` it didn't trigger the event. But it works when I added to `<v-accordion onExpand=expandCallback(index) >`. And I check the definition of `v-header`. It didn't have an attribute call `onExpand`. Is it inheritance from `v-accordion` ? The version I used is v.1.3.1
