### ISSUE TITLE
Access the accordion from the controller

### ISSUE THREAD

**Issue by Gratouille** [LukaszWatroba/v-accordion#13]
I want to access my accordion from the controller (with controllerAs syntax). I've tried with the control attribute of your accordion but I can't make it work.

How could I achieve this ?

Thx for the work :+1: 

Edit : ok so I managed to do that by passing the "control" object within a function, and it worked. Would be easier if we could directly attach a scope variable in the "control" object. My 2 cents :)

**Comment by skapi88** [comment]
Hi Gratouille,
could you please explain how you managed to do that? I tried putting the control object into a function within ng-init but that didnt work.

    <v-accordion class="vAccordion--default" control="accordion" ng-init="mc.setAccordion(control)">

and then in my MainController I did the following:

    vm.setAccordion = function (accordion) {
        accordion.toggle(2);
        accordion.toggle(3);
    };

Thanks for your help!

**Comment by Gratouille** [comment]
I've dropped this accordion for my own one, because some bugs were critical for my purposes. But I think you should try to pass "accordion" to your ng-init function, rather than "control".

**Comment by LukaszWatroba** [comment]
Hi guys! Here is an simple example of how to use vAccordion with "Controller as" syntax:

Template:
```html
<v-accordion multiple control="myCtrl.accordion">

  <v-pane ng-repeat="pane in panes" expanded="pane.expanded">
    <v-pane-header>
      <h5>{{ pane.header }}</h5>
    </v-pane-header>

    <v-pane-content>
      <p>{{ pane.content }}</p>
    </v-pane-content>
  </v-pane>

</v-accordion>

<button ng-click="vm.toggleRandomPane()">Toggle</button>
```

Controller:
```js
myApp.controller('MyController', function ($scope, $timeout) {
  var vm = this;

  vm.accordion = {};

  $scope.panes = [
    {
      header: 'Pane 1',
      content: 'Curabitur et ligula.',
      expanded: false
    },
    {
      header: 'Pane 2',
      content: 'Lorem ipsum dolor sit amet enim.',
      expanded: true
    },
    {
      header: 'Pane 3',
      content: 'Aliquam erat ac ipsum.',
      expanded: true
    }
  ];

  function rendInt (min, max) {
    return Math.floor((Math.random() * ((max + 1) - min)) + min);
  }

  function toggleRandomPane () {
    vm.accordion.toggle(rendInt(0, $scope.panes.length));
  }

  vm.toggleRandomPane = toggleRandomPane;
});
```

**Comment by LukaszWatroba** [comment]
Is this answer enough for you? Can I close this issue?

**Comment by Gratouille** [comment]
Ok for me.
