### ISSUE TITLE
The `multiple` attribute can't be found

### ISSUE THREAD

**Issue by daco** [LukaszWatroba/v-accordion#15]
When putting 'multiple' as attribute on the v-accordion element, and load the html with multiple v-pane's with already 'expanded' as attribute, I get an 'The `multiple` attribute can't be found' error.
When I omit the 'expanded' attribute, the accordion works and with multiple working. So this attribute is working.

**Comment by LukaszWatroba** [comment]
Hmm, strange. I've tested it, and everything seems to be working well. Could you post a jsfiddle?

**Comment by daco** [comment]
I'm not sure what happend, but it does seem to work. Sorry I've bothered you with this!
