### ISSUE TITLE
Customizable？

### ISSUE THREAD

**Issue by weiway** [LukaszWatroba/v-accordion#17]
Is there anyway to customize? Like color theme, animation, and etc.. ? Thank you!

**Comment by mcabe** [comment]
+1

**Comment by LukaszWatroba** [comment]
If you are using SASS, you can override the default variables, or simply create your own theme. Take a look at [this file](https://github.com/LukaszWatroba/v-accordion/blob/master/src/vAccordion/styles/_theme.scss).

```scss
// -------------------------------------
// Settings
// -------------------------------------


$v-accordion-default-theme: true !default;


// Accordion
// -------------------------------------

$v-accordion-spacing: 20px !default;

$v-pane-border-color: #D8D8D8 !default;
$v-pane-expanded-border-color: #2196F3 !default;
$v-pane-icon-color: #2196F3 !default;
$v-pane-hover-color: #2196F3 !default;
$v-pane-disabled-opacity: 0.6 !default;

$v-pane-expand-duration: 0.5s  !default;
$v-pane-hover-duration: 0.25s !default;
```

**Comment by GiTweeker** [comment]
Hi;
am not using sass.. using angular material and already declared my theme in config.. Its still not the default theme, is there a way to bind it to my theme ?

**Comment by GiTweeker** [comment]
nevermind .. compiling the sass theme to my app theme . thanks
