### ISSUE TITLE
scolling

### ISSUE THREAD

**Issue by orderofout** [LukaszWatroba/v-accordion#2]
This directive is saving me a great amount of time, for that I thank you.

However I have only one issue/request that I would normally take the time to figure out and implement myself - but I don't have the time.

Is there a simple way when expanding/collapsing panels to get the scroll position to set to the top of the newly expanded pane?

I've got about 5 panes that are all parts of a large medical form (with lots of form fields) and when one section is finished, I want to collapse it - however the scroll position remains at the bottom of the pane.

I hope that make sense. Thanks!

**Comment by LukaszWatroba** [comment]
You're welcome.

First, please upgrade vAccordion to the [v1.2.1](https://github.com/LukaszWatroba/v-accordion/releases/tag/v1.2.1) release. Then add the following code to your controller to get the top position of the currently expanded v-pane element:

```js
$scope.$on('vAccordion:onExpandAnimationEnd', function (event) {
  var paneElement = event.targetScope.paneElement;
  console.log( paneElement[0].offsetTop );
});
```

I hope this will help.
