### ISSUE TITLE
Pane Index always 2   ($parent.$index) in collapse Callback

### ISSUE THREAD

**Issue by rajancalysto** [LukaszWatroba/v-accordion#21]
Hi 

I have been using the v-accordion angularjs component. I have experiencing a issue while collapse the node.

I have 5 accordion panes. I would like to collapse the accordion panes based on some condition. In my case, always 3rd accordion pane is not able to collapsed ($index = 2 always in $parent.$index)
Any idea where to fix this?

**Comment by LukaszWatroba** [comment]
Hey!

I'm not sure if I understand you correctly but now you can expand and collapse target pane by it's `id`.

In your template:
```html
<v-accordion control="accordion">

  <v-pane id="{{ pane.id }}" ng-repeat="pane in panes">
    <v-pane-header>
      {{ ::pane.header }}
    </v-pane-header>

    <v-pane-content>
      {{ ::pane.content }}
    </v-pane-content>
  </v-pane>

</v-accordion>

<button ng-click="accordion.collapse('yourPaneId')">Collapse first pane</button>
```

Or controller:

```js
accordion.collapse('yourPaneId');
```

First, you need to download the [latest release](https://github.com/LukaszWatroba/v-accordion/releases/tag/v1.4.0) and. Sorry for the late raply.
