### ISSUE TITLE
Cannot read property 'expanded' of undefined

### ISSUE THREAD

**Issue by peter00155** [LukaszWatroba/v-accordion#22]
Im trying to display this:

     <v-accordion class="vAccordion--default" multiple>

     
      <v-pane expanded>
      <v-pane-header>
        Pane header #1
      </v-pane-header>

      <v-pane-content>
        Pane content #1
      </v-pane-content>
     </v-pane>

     
       <v-pane expanded>
         <v-pane-header>
          Pane header #2
       </v-pane-header>

       <v-pane-content>
          Pane content #2
        </v-pane-content>
       </v-pane>

    </v-accordion>

And this message appear: TypeError: Cannot read property 'expanded' of undefined. What can cause it?

**Comment by c-dante** [comment]
It's a namespace collision with `ui-bootstrap` if you're using https://angular-ui.github.io/bootstrap/

**Comment by marinbgd** [comment]
Aaaaaand how to fix this ? I want to use both libs.

**Comment by peter00155** [comment]
Define vAccordion after ui.bootstrap in angular.module. Like this:

      var myApp = angular.module('myApp', [ 'ui.bootstrap', 'vAccordion']);

**Comment by marinbgd** [comment]
Thanks. It works :)
