### ISSUE TITLE
Close child accordion content when click another parent accordion header.

### ISSUE THREAD

**Issue by shaohaolin** [LukaszWatroba/v-accordion#25]
I have 2 levels accordions. I want to collapse the level 2 content when I click level 1 accordion header.

Is it a way I can do that ? Thank you.

![accordionpage](https://cloud.githubusercontent.com/assets/6677092/10205438/38bf809a-678f-11e5-8d50-7fef821c8077.png)

Basically, what I mean is:

When I click Pane 2, the content of SubPane 1 will collapse.

**Comment by LukaszWatroba** [comment]
Hey.

Hmm, I'm not 100% sure, but something like this should do the trick:

``` html
<v-accordion multiple control="myAccordion" onexpand="expandCb(index, id)">
  <v-pane id="myPane1">
    <v-pane-header>
      First pane header
    </v-pane-header>

    <v-pane-content>
      First pane content
    </v-pane-content>
  </v-pane>

  <v-pane id="myPane2">
    <v-pane-header>
      Second pane header
    </v-pane-header>

    <v-pane-content>
      Second pane content

      <v-accordion multiple control="mySubAccordion">
        <v-pane id="mySubPane1">
          <v-pane-header>
            First subpane header
          </v-pane-header>

          <v-pane-content>
            First subpane content
          </v-pane-content>
        </v-pane>
      </v-accordion>
    </v-pane-content>
  </v-pane>
</v-accordion>
```

``` js
myApp.controller('myAccordionController', function ($scope) {
  $scope.expandCb = function (index, id) {
    if (id === 'pane1') {
      $scope.mySubAccordion.collapse('mySubPane1');
    }
  };
});
```

You need to download the [latest release](https://github.com/LukaszWatroba/v-accordion/releases/tag/v1.4.0) first. If you are still interested of course.
Sorry for the late reply!

**Comment by shaohaolin** [comment]
@LukaszWatroba  Thanks for the reply. I found a way to walk around :)

**Comment by nikhilpatteri** [comment]
I have four levels of v-accordion, and I want to close all accordions when clicked on any levels. Basically everything should be collapsed when clicked on any item. Now I'm using collapseAll() function for the first accordion, but for inner accordions, it is not working. Can anyone help me on this? Thanks in advance.
