### ISSUE TITLE
Destroy content of the pane when collapsed

### ISSUE THREAD

**Issue by slavafomin** [LukaszWatroba/v-accordion#26]
Hello!

Thank you for this great module, we are using it in one of our projects.

However, I have an issue. I have multiple panes and each pane contains a youtube video player (iframe). If you start to play the video and then collapse the pane, the video will still be playing (you can hear audio). I want to prevent this.

What is the best possible solution to this problem you will recommend? Thank you!

---

I have the following structure:

```html
<v-pane-header>
    <header>Video #1</header>
</v-pane-header>
<v-pane-content>
    <iframe
        src="https://www.youtube.com/embed/uueMI3F3jzE"
    ></iframe>
</v-pane-content>
```

I think the great solution would be to do something like this:

`<iframe ng-if="thisPane.isOpen()">`

**Comment by slavafomin** [comment]
I've managed to solve this problem using following approach:

```javascript
$scope.onExpand = function (index) {
  $scope.expandedPaneIndex = index;
};
```

```html
<iframe
    ng-if="2 == expandedPaneIndex"
></iframe>
```

It works, however, I don't really like this solution. It's pretty fragile.

**Comment by LukaszWatroba** [comment]
Hey!

Please download the latest release – [v1.4.0](https://github.com/LukaszWatroba/v-accordion/releases/tag/v1.4.0). Now you can use `$pane.isExpanded()` scope function to check whether the pane is expanded or collapsed.

Example:
```html
<v-pane-header>
    <header>Video #1</header>
</v-pane-header>
<v-pane-content>
    <iframe ng-if="$pane.isExpanded()" src="https://www.youtube.com/embed/uueMI3F3jzE"
    ></iframe>
</v-pane-content>
```

Sorry for the late reply.

**Comment by slavafomin** [comment]
You are the best Lukasz! ))
Thank's a lot )
