### ISSUE TITLE
Add a way to change the open/closed indicator

### ISSUE THREAD

**Issue by skapi88** [LukaszWatroba/v-accordion#28]
Hi,

good job on the menu. I really like using it!
It would be nice if there was a possibility to change the +/- indicatior to a custom one like arrows.

Unfortunately I cannot even find the part of the code which creates and controls the +/- or I would have changed it myself.

Thanks,
Max

**Comment by skapi88** [comment]
I figured it out myself after playing with the stylesheet.

I changed the styling rule for

    .vAccordion--default v-pane-header::after, .vAccordion--default v-pane-header::before {
        ...
    }

to (remover the ::after aswell)

     .vAccordion--default v-pane-header::before {
    content: '';
    display: block;
    position: absolute;
    top: 25%;
    right: 0;
    margin-right: 6px;
    width: 24px;
    height: 24px;
    background-image: url("../../assets/svg/ic_keyboard_arrow_down_black_24px.svg");
    ...
    }

and got a nice looking arrow which will rotate by 90° when the accordion is opened

**Comment by nikhilpatteri** [comment]
Hi,
is it possible to hide/remove the icon(+/-) for a particular row of content based on some condition. Like, if there is no child items for a <v-accordion>.
