### ISSUE TITLE
vAccoridion instead of vAccordion in emitEvent

### ISSUE THREAD

**Issue by ThomasMaij** [LukaszWatroba/v-accordion#29]
Hi,

Thanks for the great work. I was missing the event part in the angular bootstrap directives and your solution is great. I found out there's a duplicate i in vAccordion:

replace:

eventName = (angular.isDefined(accordionId)) ? accordionId + ':' + eventName : 'vAccoridion:' + eventName;

with:

eventName = (angular.isDefined(accordionId)) ? accordionId + ':' + eventName : 'vAccoridion:' + eventName;

**Comment by LukaszWatroba** [comment]
Hey,

Thanks! I just fixed the typo.
