### ISSUE TITLE
Content blacked out on expansion in Firefox 42, OSX 10.10.5

### ISSUE THREAD

**Issue by wsfuller** [LukaszWatroba/v-accordion#30]
Love this accordion but seeing an issue in Firefox 42 on OSX 10.10.5. Not sure if there is a difference in Windows or not but better to be explicit than not.  

![screen shot 2015-11-11 at 12 03 08 pm](https://cloud.githubusercontent.com/assets/3144419/11101520/326c747a-886c-11e5-80e3-bcb8ba8bb244.png)

When expanding content all the text gets a black highlight over top the text making it unreadable. See attached image. This bug is also present viewing the [demo page](http://lukaszwatroba.github.io/v-accordion/).

**Comment by kylealwyn** [comment]
Override the will-change attribute of .vAccordion--default v-pane-content > div to will-change: auto

**Comment by wsfuller** [comment]
@kylealwyn made the change

    v-pane-content > div {
      padding-bottom: $v-accordion-spacing;
      will-change: auto;
      opacity: 0;
      transform: translate3d(0, 30px, 0);
      transition: transform $v-pane-expand-duration, opacity $v-pane-expand-duration;
    }


The solid black overlay is removed but there is still a flicker. When the menu expands it will flicker the black overlay than it will be removed.
