### ISSUE TITLE
Disable toggle if no content

### ISSUE THREAD

**Issue by rajkumarpb** [LukaszWatroba/v-accordion#32]
First of all, thanks for the awesome accordion! It is quite straight-forward and no hassle in terms of usage. I have few tabs, but some of them have no content for it. In that scenario, I need to restrict the default functionality of the accordion dash and plus symbol. Can you help me achieve it?

**Comment by shyam218** [comment]
i have done something like this ..in v-accordion.css
add
.vAccordion--default v-pane-content > div {
  padding-bottom: 20px;
  will-change: transform, opacity;
  opacity: 0;
  -webkit-transform: translate3d(0, 30px, 0);
          transform: translate3d(0, 30px, 0);
  -webkit-transition: -webkit-transform 0.5s, opacity 0.5s;
          transition: transform 0.5s, opacity 0.5s; }
         v-pane.no-content v-pane-header::after, v-pane.no-content v-pane-header::before {
  display: none;
}
And use a ng-class in your html
<v-accordion id="accordionA" class="vAccordion--default"   control="accordionA" onexpand="expandCallback(index, id)" oncollapse="collapseCallback(index, id)">
	 <v-pane 
		ng-repeat="menu in menus"
		ng-class="{'no-content' : your condition}"> <v-pane-header>
	<h5 ng-click="">{{menu.name	}}</h5>
	</v-pane-header> <v-pane-content>......

**Comment by healyje** [comment]
That would be a very, very big thank you from me...

**Comment by rajkumarpb** [comment]
@shyam218 Thanks for the help! It worked for me.
