### ISSUE TITLE
Need accordion declare it in the controller

### ISSUE THREAD

**Issue by Jeevanandanj** [LukaszWatroba/v-accordion#34]
I need to declare a scope variable in the controller for this accordion. Can I do that?

**Comment by LukaszWatroba** [comment]
Not sure if this is what you're asking for, but take a look at issue [#13](https://github.com/LukaszWatroba/v-accordion/issues/13#issuecomment-134608149)

**Comment by LukaszWatroba** [comment]
Anyway, I'll close the issue, but feel free to re-open it if that is not the case.
