### ISSUE TITLE
Checkbox in header

### ISSUE THREAD

**Issue by dyaa** [LukaszWatroba/v-accordion#4]
I want to add a checkbox in the v-pane-header without toggling the accordion when i click on the checkbox, How can i make that done !

**Comment by savaa** [comment]
By CSS z-index ;)

**Comment by Rian0702** [comment]
This didnt work for me. Could you provide a sample?

**Comment by LukaszWatroba** [comment]
I fixed it finally :) Now you can add `inactive` attribute on `v-pane-header` element and create your custom toggle button, like so:

```html
<v-accordion multiple>
  <v-pane ng-repeat="pane in panes">
    <v-pane-header inactive>
      {{ ::pane.header }}
      <button ng-click="$pane.toggle()">Toggle me</button>
    </v-pane-header>

    <v-pane-content>
      {{ ::pane.content }}
    </v-pane-content>
  </v-pane>
</v-accordion>
```
