### ISSUE TITLE
No then in $animate.addClass or removeClass

### ISSUE THREAD

**Issue by ignasg** [LukaszWatroba/v-accordion#42]
Not sure which version the promises were introduced, but latest stable seems not to work. Could we get it working automatically by detecting the older version and using a pollyfill for those methods?

**Comment by LukaszWatroba** [comment]
Check [vAccordion v1.5.0](https://github.com/LukaszWatroba/v-accordion/releases/tag/v1.5.0) release. It should work without any issues.
