### ISSUE TITLE
Without Ng-Repeat it is not wokring

### ISSUE THREAD

**Issue by tamilselvanmpts** [LukaszWatroba/v-accordion#43]
Could you please give example of how to use without Ng-Repeat.

Look at the below code, id2 and id3 is not expanding.

                        <v-accordion class="vAccordion--default" >

                            <v-pane id="s1" expanded>
                                <v-pane-header>
                                    Pane header #1
                                </v-pane-header>

                                <v-pane-content>
                                    Pane content #1
                                </v-pane-content>
                            </v-pane>

                            <v-pane id="s2" expanded>
                                <v-pane-header>
                                    Pane header #2
                                </v-pane-header>

                                <v-pane-content>
                                    Pane content #2
                                </v-pane-content>
                            </v-pane>

                            <v-pane id="s3" expanded>
                                <v-pane-header>
                                    Pane header #3
                                </v-pane-header>

                                <v-pane-content>
                                    Pane content #3
                                </v-pane-content>
                            </v-pane>
                        </v-accordion>

**Comment by NHenzen** [comment]
Try adding "multiple"
`<v-accordion class="vAccordion--default" multiple>`
