### ISSUE TITLE
multiple issue

### ISSUE THREAD

**Issue by witoldszpur** [LukaszWatroba/v-accordion#45]
Hi,

after update 1.4.1 -> 1.5.1 in my case 'multiple' do not work.

**Comment by LukaszWatroba** [comment]
Hey,

in 1.5.1 the `multiple` must be empty.

```html
<v-accordion multiple>...</v-accordion>
```

**Comment by LukaszWatroba** [comment]
In the [newest (1.5.2) release](https://github.com/LukaszWatroba/v-accordion/releases/tag/v1.5.2) you can also do this: 

```html
<v-accordion multiple="true">...</v-accordion>
```

**Comment by witoldszpur** [comment]
dziekuje :)
