### ISSUE TITLE
Hi, how can i change + & - sign with up and down arrow?

### ISSUE THREAD

**Issue by christianpanea** [LukaszWatroba/v-accordion#49]
Your v-accordion is awesome thanks !

**Comment by LukaszWatroba** [comment]
Take a look at [#31](https://github.com/LukaszWatroba/v-accordion/issues/31)

**Comment by christianpanea** [comment]
Thanks, I tried to fix this problem from yesterday. I would like to obtain these arrows. Can you help me ?
![capture](https://cloud.githubusercontent.com/assets/13203612/13848060/cb5d7170-ec58-11e5-9403-c8ed09acfe49.PNG)
