### ISSUE TITLE
Nested content not showing

### ISSUE THREAD

**Issue by ofuochi** [LukaszWatroba/v-accordion#52]
Whenever I click on a pane, the "+" sign changes accordingly to the "-" sign but it does not display it's content. What am I doing wrong? Here is my code.

    <div  ng-controller="myCtrl" ng-app = "myApp">
    <v-accordion class="vAccordion--default">
        <v-pane ng-repeat="cat in categories" expanded = "false">
            <v-pane-header>
                {{ ::cat.name }}
            </v-pane-header>

            <v-pane-content>
                <p>{[{::cat.descritpion}]} This is the content</p>
            </v-pane-content>
        </v-pane>
    </v-accordion>
</div>

**Comment by LukaszWatroba** [comment]
ngAnimate is required.

**Comment by ofuochi** [comment]
Thank you. It worked.
