### ISSUE TITLE
Accesibility Issues

### ISSUE THREAD

**Issue by tameraydin** [LukaszWatroba/v-accordion#57]
Hi @LukaszWatroba,
- I see that you set tabindex=-1 on the header once it is collapsed; what is the point here? It makes collapsed headers inaccessible; it is not possible to expand it through keyboard.
- Transcluded content inside the v-content is still accessible when it is collapsed (ie. if you place a form, you can tab through fields) It should be marked as aria-hidden=true.

How likely/quickly that you merge a PR on that, if I create one? -asking this considering the last update was about 2 months ago-

**Comment by LukaszWatroba** [comment]
Hi @tameraydin!

Sorry, lack of time recently. Pull requests are welcome. I'll merge it as soon as it's ready.
