### ISSUE TITLE
$scope.expandCb is not a function

### ISSUE THREAD

**Issue by bigbo26** [LukaszWatroba/v-accordion#6]
Hello,
I have updated angular 1.4.0 and i get an error : 
```
$scope.expandCb is not a function at AccordionDirectiveController.ctrl.addPane
```

Thx for your help.

**Comment by wendannor** [comment]
You are probably missing an `onexpand` callback on your scope aren't you ?

**Comment by bigbo26** [comment]
Yes you're right ! Thx !
It works !
