### ISSUE TITLE
ng-repeat inside v-pane-content taking too much time to toggle a pane.

### ISSUE THREAD

**Issue by varungpt** [LukaszWatroba/v-accordion#63]
i am doing something like this :
`<v-pane-content>
     <div class="questionPatch" ng-repeat="something in [1,2,3,4,5,6]">
     </div>
 </v-pane-content>`

and it is taking too much time to change panes and there is no animation.

**Comment by LukaszWatroba** [comment]
Could you post a jsfiddle, to demonstrate the problem?
