### ISSUE TITLE
expandAll() not working

### ISSUE THREAD

**Issue by gilad905** [LukaszWatroba/v-accordion#80]
The function expandAll() doesn't work:
[http://codepen.io/gilad905/pen/bgENBK](http://codepen.io/gilad905/pen/bgENBK)

**Comment by katak** [comment]
It looks like you may need to add the 'multiple' attribute to your accordion element. Take a look at the error in the console.

**Comment by gilad905** [comment]
oh, silly me... you are right. Thanks
